### ISSUE TITLE
Format

### ISSUE THREAD

**Issue by andreakarasho** [KonssnoK/UO-unity_playground#9]
Hi, i've problem about file format that you written.
Can you help me?

ps: are you italian?

**Comment by KonssnoK** [comment]
Which one?


Yes I am from IT :)

**Comment by Pack4Duck** [comment]
Ciao mi chiamo Andrea!
Vorrei parlarti in pvt, visto che questa non è la sede adeguata per dei chiarimenti su dei formati!
Ti lascio un canale discord: https://discordapp.com/invite/P3Q7mKT (sono KaRaShO)

**Comment by KonssnoK** [comment]
[ITA]
sono Entrato nel canale.. 
Scrivimi in privato perchè lo trovo abbastanza affollato.

Kons#1275
